apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU= # hashing the username with base64
    mongo-root-password: cGFzc3dvcmQ= # hashing the password with base64
    # DO NOT PUT THE ORIGINAL USERNAME AND PASSWORD HERE
